name: Java CI

on:
  push:
    branches:
      - main  # 배포할 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # 사용할 JDK 버전

    - name: Build with Gradle
      run: ./gradlew build  # Gradle 빌드 명령어
      # Maven을 사용하는 경우: run: mvn package

    - name: Deploy
      run: |
        # 배포 스크립트 (예: 서버에 파일 전송)
        # scp, rsync 등을 사용하여 빌드 아티팩트를 서버로 전송할 수 있습니다.
