name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # GitHub 저장소에서 코드를 가져옵니다.

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Node.js 버전 설정

    - name: Install dependencies
      run: npm install  # 의존성 설치

    - name: Build the project
      run: npm run build  # 프로젝트 빌드 (필요한 경우)

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3  # SSH를 통해 EC2에 배포
      with:
        host: ${{ secrets.AWS_EC2_HOST }}  # GitHub Secrets에서 EC2의 호스트 정보 사용
        username: ec2-user  # EC2 사용자명 (일반적으로 'ec2-user')
        key: ${{ secrets.AWS_EC2_SSH_KEY }}  # EC2 SSH 프라이빗 키를 GitHub Secrets에서 사용
        script: |
          cd /home/ec2-user/your-app-directory
          git pull origin main
          npm install
          pm2 restart your-app  # PM2를 사용하여 애플리케이션 재시작 (필요한 경우)
