name: Deploy to EC2

# main 브랜치에 푸시될 때마다 자동으로 배포
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 저장소에서 최신 코드를 가져옵니다.
    - name: Checkout the code
      uses: actions/checkout@v2

    # 2. AWS CLI 설정을 위해 AWS 자격 증명을 설정합니다.
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2  # 한국 리전(서울)

    # 3. SSH를 통해 EC2 인스턴스에 접속하여 배포 작업을 실행합니다.
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.3  # SSH를 통해 EC2에 연결하는 액션
      with:
        host: ${{ secrets.AWS_EC2_HOST }}  # GitHub Secrets에 저장된 EC2의 퍼블릭 IP 주소 또는 DNS
        username: ec2-user  # EC2의 기본 사용자 (Amazon Linux의 경우 'ec2-user')
        key: ${{ secrets.AWS_EC2_SSH_KEY }}  # GitHub Secrets에 저장된 프라이빗 SSH 키
        port: 22  # 기본 SSH 포트
        script: |
          cd /home/ec2-user/your-app-directory  # EC2 인스턴스의 애플리케이션 디렉토리로 이동
          git pull origin main  # 최신 코드를 GitHub에서 가져옵니다.
          npm install  # 프로젝트 의존성을 설치합니다.
          pm2 restart your-app  # PM2를 사용해 애플리케이션을 재시작합니다. (필요에 따라 수정)
